tasks:
  - init: |
      pyenv local 3.7.7
      cd dawn
      mkdir build && cd build
      cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython3_EXECTUABLE=`which python`
      ln -s $(pwd)/compile_commands.json /workspace/dawn
